"""
Canonical connector registry for runtime, evidence metadata, and frontend labels.

This is the single source of truth for:
  - runtime-active connector ordering
  - human-readable connector labels/categories/descriptions
  - source metadata used by evidence and rules layers

Frontend connector metadata is generated from this registry via
`scripts/generate_frontend_connectors.py`.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ConnectorRegistryEntry:
    label: str
    category: str
    description: str
    source_class: str = "public_connector"
    authority_level: str = "third_party_public"
    access_model: str = "public_api"
    runtime_active: bool = False


CONNECTOR_REGISTRY: dict[str, ConnectorRegistryEntry] = {
    "international_exhibitors_fixture": ConnectorRegistryEntry(
        label="International Exhibitors Fixture",
        category="Collector",
        description="Replayable analyst-curated defense exhibitor fixture with provenance metadata",
        source_class="analyst_fixture",
        authority_level="analyst_curated_fixture",
        access_model="local_json_fixture",
        runtime_active=True,
    ),
    "contract_opportunities_archive_fixture": ConnectorRegistryEntry(
        label="Contract Opportunities Archive Fixture",
        category="Collector",
        description="Replayable archive-and-diff fixture for contract vehicle lineage and recompete context",
        source_class="analyst_fixture",
        authority_level="analyst_curated_fixture",
        access_model="local_json_fixture",
    ),
    "contract_opportunities_public": ConnectorRegistryEntry(
        label="Contract Opportunities Public",
        category="Collector",
        description="Seeded official opportunity notice pages parsed for contract family, customer, and performance signals",
        source_class="public_connector",
        authority_level="official_program_system",
        access_model="public_html",
    ),
    "gao_bid_protests_fixture": ConnectorRegistryEntry(
        label="GAO Bid Protests Fixture",
        category="Collector",
        description="Replayable GAO bid protest fixture for contract vehicle legal pressure and protest posture",
        source_class="analyst_fixture",
        authority_level="official_program_system",
        access_model="local_json_fixture",
    ),
    "gao_bid_protests_public": ConnectorRegistryEntry(
        label="GAO Bid Protests Public",
        category="Collector",
        description="Seeded official GAO docket and decision pages captured through browser render for protest posture",
        source_class="public_connector",
        authority_level="official_program_system",
        access_model="browser_rendered_public_html",
    ),
    "public_html_contract_vehicle": ConnectorRegistryEntry(
        label="Public HTML Contract Vehicle",
        category="Collector",
        description="Analyst-seeded public or archived contract-vehicle pages parsed for lineage, customer, and performance signals",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_html",
    ),
    "contract_vehicle_wayback": ConnectorRegistryEntry(
        label="Contract Vehicle Wayback",
        category="Collector",
        description="Seeded Internet Archive capture retrieval for contract-vehicle lineage and recompete context",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_archive",
    ),
    "usaspending_vehicle_live": ConnectorRegistryEntry(
        label="USAspending Vehicle Live",
        category="Collector",
        description="Live USAspending vehicle search that surfaces current primes, subs, and funding path without seeded notice pages",
        source_class="public_connector",
        authority_level="official_program_system",
        access_model="public_api",
    ),
    "usaspending_vendor_live": ConnectorRegistryEntry(
        label="USAspending Vendor Live",
        category="Collector",
        description="Live USAspending vendor procurement footprint covering prime vehicles, sub vehicles, teammate recurrence, and customer concentration",
        source_class="public_connector",
        authority_level="official_program_system",
        access_model="public_api",
    ),
    "dod_sam_exclusions": ConnectorRegistryEntry(
        label="DoD EPLS Exclusions",
        category="Sanctions",
        description="DoD SAM exclusions and EPLS checks",
        source_class="public_connector",
        authority_level="official_program_system",
        access_model="public_api",
        runtime_active=True,
    ),
    "trade_csl": ConnectorRegistryEntry(
        label="Consolidated Screening List",
        category="Sanctions",
        description="US government consolidated screening lists",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
        runtime_active=True,
    ),
    "un_sanctions": ConnectorRegistryEntry(
        label="UN Sanctions",
        category="Sanctions",
        description="UN Security Council sanctions feed",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
        runtime_active=True,
    ),
    "opensanctions_pep": ConnectorRegistryEntry(
        label="OpenSanctions PEP",
        category="Sanctions",
        description="Politically exposed person screening",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_api",
        runtime_active=True,
    ),
    "worldbank_debarred": ConnectorRegistryEntry(
        label="World Bank Debarments",
        category="Sanctions",
        description="Multilateral development bank debarments",
        source_class="public_connector",
        authority_level="official_program_system",
        access_model="public_api",
        runtime_active=True,
    ),
    "icij_offshore": ConnectorRegistryEntry(
        label="ICIJ Offshore Leaks",
        category="Ownership",
        description="Panama, Paradise, and Pandora Papers",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_api",
        runtime_active=True,
    ),
    "fara": ConnectorRegistryEntry(
        label="DOJ FARA",
        category="Government",
        description="Foreign Agents Registration Act filings",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
        runtime_active=True,
    ),
    "gdelt_media": ConnectorRegistryEntry(
        label="GDELT Adverse Media",
        category="Media",
        description="Global adverse media monitoring",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_api",
        runtime_active=True,
    ),
    "google_news": ConnectorRegistryEntry(
        label="Google News",
        category="Media",
        description="Real-time public news coverage",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_feed",
        runtime_active=True,
    ),
    "rss_public": ConnectorRegistryEntry(
        label="First-Party RSS Feed",
        category="Collector",
        description="Seeded or discovered first-party RSS and Atom feeds parsed for contract, assurance, and activity signals",
        source_class="public_connector",
        authority_level="first_party_self_disclosed",
        access_model="rss_public",
        runtime_active=True,
    ),
    "sec_edgar": ConnectorRegistryEntry(
        label="SEC EDGAR",
        category="Financial",
        description="SEC filings and public-company metadata",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
        runtime_active=True,
    ),
    "gleif_lei": ConnectorRegistryEntry(
        label="GLEIF LEI",
        category="Ownership",
        description="Legal Entity Identifier registry",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="public_api",
        runtime_active=True,
    ),
    "gleif_bods_ownership_fixture": ConnectorRegistryEntry(
        label="GLEIF / BODS Ownership Fixture",
        category="Ownership",
        description="Replayable standards-backed ownership and control-path fixture",
        source_class="analyst_fixture",
        authority_level="standards_modeled_fixture",
        access_model="local_json_fixture",
        runtime_active=True,
    ),
    "openownership_bods_fixture": ConnectorRegistryEntry(
        label="Open Ownership BODS Fixture",
        category="Ownership",
        description="Replayable BODS beneficial ownership and control statements",
        source_class="analyst_fixture",
        authority_level="standards_modeled_fixture",
        access_model="local_json_fixture",
        runtime_active=True,
    ),
    "openownership_bods_public": ConnectorRegistryEntry(
        label="Open Ownership BODS Public",
        category="Ownership",
        description="Public BODS dataset ingestion from Open Ownership style JSON",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_json",
        runtime_active=True,
    ),
    "opencorporates": ConnectorRegistryEntry(
        label="OpenCorporates",
        category="Ownership",
        description="Global corporate registry data",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_api",
        runtime_active=True,
    ),
    "uk_companies_house": ConnectorRegistryEntry(
        label="UK Companies House",
        category="Ownership",
        description="UK beneficial ownership and filings",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="public_api",
        runtime_active=True,
    ),
    "corporations_canada": ConnectorRegistryEntry(
        label="Corporations Canada",
        category="Ownership",
        description="Canadian federal corporations, directors, and ISC disclosures",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="public_json",
        runtime_active=True,
    ),
    "australia_abn_asic": ConnectorRegistryEntry(
        label="Australia ABN / ASIC",
        category="Ownership",
        description="Australian Business Register and ASIC identity corroboration",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="public_json",
        runtime_active=True,
    ),
    "singapore_acra": ConnectorRegistryEntry(
        label="Singapore ACRA",
        category="Ownership",
        description="Singapore ACRA entity profile and official identity corroboration",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="public_json",
        runtime_active=True,
    ),
    "new_zealand_companies_office": ConnectorRegistryEntry(
        label="New Zealand Companies Office / NZBN",
        category="Ownership",
        description="New Zealand Companies Register and NZBN identity corroboration",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="public_json",
        runtime_active=True,
    ),
    "norway_brreg": ConnectorRegistryEntry(
        label="Norway Brreg",
        category="Ownership",
        description="Bronnoysund Register Centre organisation data and gated beneficial-owner corroboration",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="public_json",
        runtime_active=True,
    ),
    "netherlands_kvk": ConnectorRegistryEntry(
        label="Netherlands KVK",
        category="Ownership",
        description="Dutch Chamber of Commerce entity profile and mutation corroboration",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="public_json",
        runtime_active=True,
    ),
    "france_inpi_rne": ConnectorRegistryEntry(
        label="France INPI / RNE",
        category="Ownership",
        description="French RNE identity corroboration with gated beneficial-owner access",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="gated_api",
        runtime_active=True,
    ),
    "wikidata_company": ConnectorRegistryEntry(
        label="Wikidata Company",
        category="Ownership",
        description="Public knowledge graph company metadata",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_api",
        runtime_active=True,
    ),
    "public_html_ownership": ConnectorRegistryEntry(
        label="Public HTML Ownership",
        category="Ownership",
        description="First-party company-site ownership and parentage hints from public HTML",
        source_class="public_connector",
        authority_level="first_party_self_disclosed",
        access_model="public_html",
        runtime_active=True,
    ),
    "public_search_ownership": ConnectorRegistryEntry(
        label="Public Search Ownership",
        category="Ownership",
        description="Public search discovery of official websites routed into first-party HTML ownership checks",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="search_public_html",
        runtime_active=True,
    ),
    "sam_gov": ConnectorRegistryEntry(
        label="SAM.gov Registration",
        category="Government",
        description="US federal entity registration, UEI, CAGE, and integrity data",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="public_api",
        runtime_active=True,
    ),
    "sam_subaward_reporting": ConnectorRegistryEntry(
        label="SAM.gov Subaward Reporting",
        category="Government",
        description="US federal subcontract and subaward reporting data",
        source_class="public_connector",
        authority_level="official_program_system",
        access_model="public_api",
        runtime_active=True,
    ),
    "usaspending": ConnectorRegistryEntry(
        label="USASpending",
        category="Government",
        description="Federal spending and award history",
        source_class="public_connector",
        authority_level="official_program_system",
        access_model="public_api",
        runtime_active=True,
    ),
    "fpds_contracts": ConnectorRegistryEntry(
        label="FPDS Contracts",
        category="Government",
        description="Federal procurement contract history",
        source_class="public_connector",
        authority_level="official_program_system",
        access_model="public_api",
        runtime_active=True,
    ),
    "epa_echo": ConnectorRegistryEntry(
        label="EPA ECHO",
        category="Compliance",
        description="EPA enforcement and compliance history",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
        runtime_active=True,
    ),
    "osha_safety": ConnectorRegistryEntry(
        label="OSHA Safety",
        category="Compliance",
        description="OSHA workplace safety records",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
        runtime_active=True,
    ),
    "courtlistener": ConnectorRegistryEntry(
        label="CourtListener",
        category="Legal",
        description="Litigation and court records",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_api",
        runtime_active=True,
    ),
    "recap_courts": ConnectorRegistryEntry(
        label="RECAP Federal Litigation",
        category="Legal",
        description="Federal litigation archive and docket history",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_api",
        runtime_active=True,
    ),
    "fdic_bankfind": ConnectorRegistryEntry(
        label="FDIC BankFind",
        category="Financial",
        description="FDIC bank and institution data",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="public_api",
        runtime_active=True,
    ),
    "cisa_kev": ConnectorRegistryEntry(
        label="CISA KEV",
        category="Compliance",
        description="Known Exploited Vulnerabilities catalog",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
        runtime_active=True,
    ),
    "mitre_attack_fixture": ConnectorRegistryEntry(
        label="MITRE ATT&CK Fixture",
        category="Threat Intel",
        description="Replayable ATT&CK techniques, tactics, and actor context",
        source_class="analyst_fixture",
        authority_level="third_party_public",
        access_model="local_json_fixture",
        runtime_active=True,
    ),
    "cisa_advisory_fixture": ConnectorRegistryEntry(
        label="CISA Advisory Fixture",
        category="Threat Intel",
        description="Replayable CISA advisory corpus with sectors, mitigations, and TTP mappings",
        source_class="analyst_fixture",
        authority_level="official_regulatory",
        access_model="local_json_fixture",
        runtime_active=True,
    ),
    "cyclonedx_spdx_vex_fixture": ConnectorRegistryEntry(
        label="CycloneDX / SPDX / VEX Fixture",
        category="Cyber",
        description="Replayable standards-backed cyber supply-chain depth fixture",
        source_class="analyst_fixture",
        authority_level="standards_modeled_fixture",
        access_model="local_json_fixture",
        runtime_active=True,
    ),
    "public_assurance_evidence_fixture": ConnectorRegistryEntry(
        label="Public Assurance Evidence Fixture",
        category="Cyber",
        description="Replayable first-party public assurance evidence for SBOM, VEX, provenance, and lifecycle posture",
        source_class="analyst_fixture",
        authority_level="first_party_self_disclosed",
        access_model="local_json_fixture",
        runtime_active=True,
    ),
    "osv_dev": ConnectorRegistryEntry(
        label="OSV.dev",
        category="Cyber",
        description="Open source package vulnerability lookups for declared package inventory",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_api",
        runtime_active=True,
    ),
    "deps_dev": ConnectorRegistryEntry(
        label="deps.dev",
        category="Cyber",
        description="Open source package, advisory, provenance, and repository metadata",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_api",
        runtime_active=True,
    ),
    "openssf_scorecard": ConnectorRegistryEntry(
        label="OpenSSF Scorecard",
        category="Cyber",
        description="Repository security posture for declared source repositories",
        source_class="public_connector",
        authority_level="third_party_public",
        access_model="public_api",
        runtime_active=True,
    ),
    "ofac_sdn": ConnectorRegistryEntry(
        label="OFAC SDN",
        category="Sanctions",
        description="Treasury Specially Designated Nationals",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
        runtime_active=True,
    ),
    "eu_sanctions": ConnectorRegistryEntry(
        label="EU Sanctions",
        category="Sanctions",
        description="European Commission sanctions feed",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
        runtime_active=True,
    ),
    "uk_hmt_sanctions": ConnectorRegistryEntry(
        label="UK HMT Sanctions",
        category="Sanctions",
        description="UK HM Treasury sanctions feed",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
        runtime_active=True,
    ),
    "sbir_awards": ConnectorRegistryEntry(
        label="SBIR Awards",
        category="Government",
        description="SBIR and STTR award history",
        source_class="public_connector",
        authority_level="official_program_system",
        access_model="public_api",
        runtime_active=True,
    ),
    "sec_xbrl": ConnectorRegistryEntry(
        label="SEC XBRL",
        category="Financial",
        description="Structured SEC financial data",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
        runtime_active=True,
    ),
    "cross_correlation": ConnectorRegistryEntry(
        label="Cross-Correlation Analysis",
        category="Derived",
        description="Derived correlation across multiple evidence sources",
        source_class="derived_analysis",
        authority_level="derived_rules",
        access_model="rules_dataset",
    ),
    "bis_rules_engine": ConnectorRegistryEntry(
        label="BIS Rules Engine",
        category="Rules",
        description="Export authorization rules and regulatory posture logic",
        source_class="rules_layer",
        authority_level="derived_rules",
        access_model="rules_dataset",
    ),
    "nvd_overlay": ConnectorRegistryEntry(
        label="NVD Overlay",
        category="Compliance",
        description="NIST NVD product and vulnerability overlay",
        source_class="public_connector",
        authority_level="official_regulatory",
        access_model="public_api",
    ),
    "sprs_import": ConnectorRegistryEntry(
        label="SPRS Import",
        category="Customer Evidence",
        description="Customer-provided supplier performance and CMMC evidence",
        source_class="gated_federal_source",
        authority_level="official_program_system",
        access_model="customer_upload",
    ),
    "oscal_upload": ConnectorRegistryEntry(
        label="OSCAL Upload",
        category="Customer Evidence",
        description="Customer-provided SSP or POA&M artifact",
        source_class="customer_artifact",
        authority_level="customer_attested",
        access_model="customer_upload",
    ),
    "foci_artifact_upload": ConnectorRegistryEntry(
        label="FOCI Artifact Upload",
        category="Customer Evidence",
        description="Customer-provided Form 328, ownership, or mitigation evidence",
        source_class="customer_artifact",
        authority_level="customer_attested",
        access_model="customer_upload",
    ),
    "export_artifact_upload": ConnectorRegistryEntry(
        label="Export Artifact Upload",
        category="Customer Evidence",
        description="Customer-provided export classification, license, or access-control evidence",
        source_class="customer_artifact",
        authority_level="customer_internal_record",
        access_model="customer_upload",
    ),
    "piee_sprs": ConnectorRegistryEntry(
        label="PIEE / SPRS",
        category="Government",
        description="Authenticated DoD supplier performance and cyber posture source",
        source_class="gated_federal_source",
        authority_level="official_program_system",
        access_model="authenticated_api",
    ),
    "dla_cage": ConnectorRegistryEntry(
        label="DLA CAGE",
        category="Government",
        description="Defense Logistics Agency CAGE registry source",
        source_class="public_connector",
        authority_level="official_registry",
        access_model="public_api",
    ),
    "fedramp_marketplace": ConnectorRegistryEntry(
        label="FedRAMP Marketplace",
        category="Government",
        description="FedRAMP authorization and cloud service posture source",
        source_class="public_connector",
        authority_level="official_program_system",
        access_model="public_api",
    ),
    "careers_scraper": ConnectorRegistryEntry(
        label="Careers Scraper (AXIOM)",
        category="Grey Zone OSINT",
        description="Job board and careers page scraper for subcontractor identification. Primary source when SAM Subaward API fails (FEDSIM vehicles).",
        source_class="grey_zone_osint",
        authority_level="third_party_public",
        access_model="public_scrape",
        runtime_active=True,
    ),
}


ACTIVE_CONNECTOR_ORDER: list[str] = [
    "international_exhibitors_fixture",
    "dod_sam_exclusions",
    "trade_csl",
    "un_sanctions",
    "opensanctions_pep",
    "worldbank_debarred",
    "icij_offshore",
    "fara",
    "gdelt_media",
    "google_news",
    "rss_public",
    "sec_edgar",
    "gleif_lei",
    "gleif_bods_ownership_fixture",
    "openownership_bods_fixture",
    "openownership_bods_public",
    "opencorporates",
    "uk_companies_house",
    "corporations_canada",
    "australia_abn_asic",
    "singapore_acra",
    "new_zealand_companies_office",
    "norway_brreg",
    "netherlands_kvk",
    "france_inpi_rne",
    "wikidata_company",
    "public_search_ownership",
    "public_html_ownership",
    "sam_gov",
    "sam_subaward_reporting",
    "usaspending",
    "fpds_contracts",
    "epa_echo",
    "osha_safety",
    "courtlistener",
    "fdic_bankfind",
    "cisa_kev",
    "mitre_attack_fixture",
    "cisa_advisory_fixture",
    "cyclonedx_spdx_vex_fixture",
    "public_assurance_evidence_fixture",
    "osv_dev",
    "deps_dev",
    "openssf_scorecard",
    "ofac_sdn",
    "eu_sanctions",
    "uk_hmt_sanctions",
    "sbir_awards",
    "sec_xbrl",
    "recap_courts",
    "careers_scraper",
]

ACTIVE_CONNECTOR_NAMES = tuple(ACTIVE_CONNECTOR_ORDER)


def get_connector_entry(name: str) -> ConnectorRegistryEntry | None:
    return CONNECTOR_REGISTRY.get(name)


def get_frontend_connector_meta() -> dict[str, dict[str, str]]:
    return {
        name: {
            "label": entry.label,
            "category": entry.category,
            "description": entry.description,
        }
        for name, entry in CONNECTOR_REGISTRY.items()
    }


def get_source_metadata_defaults(name: str) -> dict[str, str]:
    entry = CONNECTOR_REGISTRY.get(name)
    if not entry:
        return {
            "source_class": "public_connector",
            "authority_level": "third_party_public",
            "access_model": "public_api",
        }
    return {
        "source_class": entry.source_class,
        "authority_level": entry.authority_level,
        "access_model": entry.access_model,
    }


_missing_active = [name for name in ACTIVE_CONNECTOR_ORDER if name not in CONNECTOR_REGISTRY]
if _missing_active:
    raise RuntimeError(f"ACTIVE_CONNECTOR_ORDER references unknown connectors: {_missing_active}")
