export const CONNECTOR_META = {
  dod_sam_exclusions: { label: "DoD EPLS Exclusions", category: "Sanctions", description: "DoD SAM exclusions and EPLS checks" },
  trade_csl: { label: "Consolidated Screening List", category: "Sanctions", description: "US government consolidated screening lists" },
  un_sanctions: { label: "UN Sanctions", category: "Sanctions", description: "UN Security Council sanctions feed" },
  opensanctions_pep: { label: "OpenSanctions PEP", category: "Sanctions", description: "Politically exposed person screening" },
  worldbank_debarred: { label: "World Bank Debarments", category: "Sanctions", description: "Multilateral development bank debarments" },
  icij_offshore: { label: "ICIJ Offshore Leaks", category: "Ownership", description: "Panama, Paradise, and Pandora Papers" },
  fara: { label: "DOJ FARA", category: "Government", description: "Foreign Agents Registration Act filings" },
  gdelt_media: { label: "GDELT Adverse Media", category: "Media", description: "Global adverse media monitoring" },
  google_news: { label: "Google News", category: "Media", description: "Real-time public news coverage" },
  sec_edgar: { label: "SEC EDGAR", category: "Financial", description: "SEC filings and public-company metadata" },
  gleif_lei: { label: "GLEIF LEI", category: "Ownership", description: "Legal Entity Identifier registry" },
  opencorporates: { label: "OpenCorporates", category: "Ownership", description: "Global corporate registry data" },
  uk_companies_house: { label: "UK Companies House", category: "Ownership", description: "UK beneficial ownership and filings" },
  wikidata_company: { label: "Wikidata Company", category: "Ownership", description: "Public knowledge graph company metadata" },
  sam_gov: { label: "SAM.gov", category: "Government", description: "US federal vendor registration data" },
  usaspending: { label: "USASpending", category: "Government", description: "Federal spending and award history" },
  fpds_contracts: { label: "FPDS Contracts", category: "Government", description: "Federal procurement contract history" },
  epa_echo: { label: "EPA ECHO", category: "Compliance", description: "EPA enforcement and compliance history" },
  osha_safety: { label: "OSHA Safety", category: "Compliance", description: "OSHA workplace safety records" },
  courtlistener: { label: "CourtListener", category: "Legal", description: "Litigation and court records" },
  fdic_bankfind: { label: "FDIC BankFind", category: "Financial", description: "FDIC bank and institution data" },
  cisa_kev: { label: "CISA KEV", category: "Compliance", description: "Known Exploited Vulnerabilities catalog" },
  ofac_sdn: { label: "OFAC SDN", category: "Sanctions", description: "Treasury Specially Designated Nationals" },
  eu_sanctions: { label: "EU Sanctions", category: "Sanctions", description: "European Commission sanctions feed" },
  uk_hmt_sanctions: { label: "UK HMT Sanctions", category: "Sanctions", description: "UK HM Treasury sanctions feed" },
  sbir_awards: { label: "SBIR Awards", category: "Government", description: "SBIR and STTR award history" },
  sec_xbrl: { label: "SEC XBRL", category: "Financial", description: "Structured SEC financial data" },
} as const;

export type ConnectorName = keyof typeof CONNECTOR_META;
