// Generated from backend/osint/connector_registry.py. Do not edit manually.
export const CONNECTOR_META = {
  international_exhibitors_fixture: { label: "International Exhibitors Fixture", category: "Collector", description: "Replayable analyst-curated defense exhibitor fixture with provenance metadata" },
  dod_sam_exclusions: { label: "DoD EPLS Exclusions", category: "Sanctions", description: "DoD SAM exclusions and EPLS checks" },
  trade_csl: { label: "Consolidated Screening List", category: "Sanctions", description: "US government consolidated screening lists" },
  un_sanctions: { label: "UN Sanctions", category: "Sanctions", description: "UN Security Council sanctions feed" },
  opensanctions_pep: { label: "OpenSanctions PEP", category: "Sanctions", description: "Politically exposed person screening" },
  worldbank_debarred: { label: "World Bank Debarments", category: "Sanctions", description: "Multilateral development bank debarments" },
  icij_offshore: { label: "ICIJ Offshore Leaks", category: "Ownership", description: "Panama, Paradise, and Pandora Papers" },
  fara: { label: "DOJ FARA", category: "Government", description: "Foreign Agents Registration Act filings" },
  gdelt_media: { label: "GDELT Adverse Media", category: "Media", description: "Global adverse media monitoring" },
  google_news: { label: "Google News", category: "Media", description: "Real-time public news coverage" },
  sec_edgar: { label: "SEC EDGAR", category: "Financial", description: "SEC filings and public-company metadata" },
  gleif_lei: { label: "GLEIF LEI", category: "Ownership", description: "Legal Entity Identifier registry" },
  gleif_bods_ownership_fixture: { label: "GLEIF / BODS Ownership Fixture", category: "Ownership", description: "Replayable standards-backed ownership and control-path fixture" },
  openownership_bods_fixture: { label: "Open Ownership BODS Fixture", category: "Ownership", description: "Replayable BODS beneficial ownership and control statements" },
  openownership_bods_public: { label: "Open Ownership BODS Public", category: "Ownership", description: "Public BODS dataset ingestion from Open Ownership style JSON" },
  opencorporates: { label: "OpenCorporates", category: "Ownership", description: "Global corporate registry data" },
  uk_companies_house: { label: "UK Companies House", category: "Ownership", description: "UK beneficial ownership and filings" },
  corporations_canada: { label: "Corporations Canada", category: "Ownership", description: "Canadian federal corporations, directors, and ISC disclosures" },
  australia_abn_asic: { label: "Australia ABN / ASIC", category: "Ownership", description: "Australian Business Register and ASIC identity corroboration" },
  singapore_acra: { label: "Singapore ACRA", category: "Ownership", description: "Singapore ACRA entity profile and official identity corroboration" },
  new_zealand_companies_office: { label: "New Zealand Companies Office / NZBN", category: "Ownership", description: "New Zealand Companies Register and NZBN identity corroboration" },
  norway_brreg: { label: "Norway Brreg", category: "Ownership", description: "Bronnoysund Register Centre organisation data and gated beneficial-owner corroboration" },
  netherlands_kvk: { label: "Netherlands KVK", category: "Ownership", description: "Dutch Chamber of Commerce entity profile and mutation corroboration" },
  france_inpi_rne: { label: "France INPI / RNE", category: "Ownership", description: "French RNE identity corroboration with gated beneficial-owner access" },
  wikidata_company: { label: "Wikidata Company", category: "Ownership", description: "Public knowledge graph company metadata" },
  public_html_ownership: { label: "Public HTML Ownership", category: "Ownership", description: "First-party company-site ownership and parentage hints from public HTML" },
  public_search_ownership: { label: "Public Search Ownership", category: "Ownership", description: "Public search discovery of official websites routed into first-party HTML ownership checks" },
  sam_gov: { label: "SAM.gov Registration", category: "Government", description: "US federal entity registration, UEI, CAGE, and integrity data" },
  sam_subaward_reporting: { label: "SAM.gov Subaward Reporting", category: "Government", description: "US federal subcontract and subaward reporting data" },
  usaspending: { label: "USASpending", category: "Government", description: "Federal spending and award history" },
  fpds_contracts: { label: "FPDS Contracts", category: "Government", description: "Federal procurement contract history" },
  epa_echo: { label: "EPA ECHO", category: "Compliance", description: "EPA enforcement and compliance history" },
  osha_safety: { label: "OSHA Safety", category: "Compliance", description: "OSHA workplace safety records" },
  courtlistener: { label: "CourtListener", category: "Legal", description: "Litigation and court records" },
  recap_courts: { label: "RECAP Federal Litigation", category: "Legal", description: "Federal litigation archive and docket history" },
  fdic_bankfind: { label: "FDIC BankFind", category: "Financial", description: "FDIC bank and institution data" },
  cisa_kev: { label: "CISA KEV", category: "Compliance", description: "Known Exploited Vulnerabilities catalog" },
  mitre_attack_fixture: { label: "MITRE ATT&CK Fixture", category: "Threat Intel", description: "Replayable ATT&CK techniques, tactics, and actor context" },
  cisa_advisory_fixture: { label: "CISA Advisory Fixture", category: "Threat Intel", description: "Replayable CISA advisory corpus with sectors, mitigations, and TTP mappings" },
  cyclonedx_spdx_vex_fixture: { label: "CycloneDX / SPDX / VEX Fixture", category: "Cyber", description: "Replayable standards-backed cyber supply-chain depth fixture" },
  public_assurance_evidence_fixture: { label: "Public Assurance Evidence Fixture", category: "Cyber", description: "Replayable first-party public assurance evidence for SBOM, VEX, provenance, and lifecycle posture" },
  osv_dev: { label: "OSV.dev", category: "Cyber", description: "Open source package vulnerability lookups for declared package inventory" },
  deps_dev: { label: "deps.dev", category: "Cyber", description: "Open source package, advisory, provenance, and repository metadata" },
  openssf_scorecard: { label: "OpenSSF Scorecard", category: "Cyber", description: "Repository security posture for declared source repositories" },
  ofac_sdn: { label: "OFAC SDN", category: "Sanctions", description: "Treasury Specially Designated Nationals" },
  eu_sanctions: { label: "EU Sanctions", category: "Sanctions", description: "European Commission sanctions feed" },
  uk_hmt_sanctions: { label: "UK HMT Sanctions", category: "Sanctions", description: "UK HM Treasury sanctions feed" },
  sbir_awards: { label: "SBIR Awards", category: "Government", description: "SBIR and STTR award history" },
  sec_xbrl: { label: "SEC XBRL", category: "Financial", description: "Structured SEC financial data" },
  cross_correlation: { label: "Cross-Correlation Analysis", category: "Derived", description: "Derived correlation across multiple evidence sources" },
  bis_rules_engine: { label: "BIS Rules Engine", category: "Rules", description: "Export authorization rules and regulatory posture logic" },
  nvd_overlay: { label: "NVD Overlay", category: "Compliance", description: "NIST NVD product and vulnerability overlay" },
  sprs_import: { label: "SPRS Import", category: "Customer Evidence", description: "Customer-provided supplier performance and CMMC evidence" },
  oscal_upload: { label: "OSCAL Upload", category: "Customer Evidence", description: "Customer-provided SSP or POA&M artifact" },
  foci_artifact_upload: { label: "FOCI Artifact Upload", category: "Customer Evidence", description: "Customer-provided Form 328, ownership, or mitigation evidence" },
  export_artifact_upload: { label: "Export Artifact Upload", category: "Customer Evidence", description: "Customer-provided export classification, license, or access-control evidence" },
  piee_sprs: { label: "PIEE / SPRS", category: "Government", description: "Authenticated DoD supplier performance and cyber posture source" },
  dla_cage: { label: "DLA CAGE", category: "Government", description: "Defense Logistics Agency CAGE registry source" },
  fedramp_marketplace: { label: "FedRAMP Marketplace", category: "Government", description: "FedRAMP authorization and cloud service posture source" },
} as const;

export type ConnectorName = keyof typeof CONNECTOR_META;
